name: Release

on:
  release:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make dependencies
      
    - name: Build
      run: |
        make all VERSION=${{ github.ref_name }}
        
    - name: Upload Release
      run: |
        tar -cJf swr-release-${{ github.ref_name }}.tar.xz data docs bin web LICENSE
      uses: actions/upload-artifact@v3
      with:
        name: swr-release-${{ github.ref_name }}.tar.xz
        path: swr-release-${{ github.ref_name }}.tar.xz

    
