name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: swr-release-linux-${{ github.ref_name }}.tar.xz
          - os: macos-latest
            asset_name: swr-release-macos-${{ github.ref_name }}.tar.xz
          - os: windows-latest
            asset_name: swr-release-win64-${{ github.ref_name }}.zip

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make dependencies
      
    - name: Build Windows
      if: startsWith(matrix.os, 'windows')
      run: |
        make all VERSION=${{ github.ref_name }}
        tar -czf ${{ matrix.asset_name }} data docs bin web LICENSE
    - name: Build BSD
      if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')
      run: |
        make all VERSION=${{ github.ref_name }}
        tar -cJf ${{ matrix.asset_name }} data docs bin web LICENSE
        
    - name: Publish Server Archive
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.asset_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
