name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: server
            asset_name: swr-release-linux-
          - os: macos-latest
            artifact_name: server
            asset_name: swr-release-macos-

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: make dependencies
      
    - name: Build
      run: |
        make VERSION=${{ github.ref_name }}
        tar -cJf ${{ matrix.asset_name }}${{ github.ref_name }}.tar.xz data docs bin web LICENSE
        
    - name: Publish
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.asset_name }}${{ github.ref_name }}.tar.xz
        asset_name: ${{ matrix.asset_name }}${{ github.ref_name }}.tar.xz
        tag: ${{ github.ref }}
    
